feat: Create self-introduction
kimdaehee90/git_HW pull request #1
Opened 2021-07-21 11:17 UTC by kimdaehee90

Leave a comment
This is my self-introduction

2021-07-21 13:04 UTC, burnyst requested changes

2021-07-21 13:04 UTC, burnyst commented on self-introduction.html
> +<!DOCTYPE html>
good job

2021-07-21 13:57 UTC, burnyst approved these changes

2021-07-21 13:57 UTC, burnyst commented on self-introduction.html
> +        대화하는것을 좋아하여 커피와 술도 좋아합니다.
great

2021-07-21 14:15 UTC, burnyst requested changes

2021-07-21 14:15 UTC, burnyst commented on self-introduction.html
> +자기소개서
This is unnecessary

2021-07-21 14:16 UTC, burnyst commented on self-introduction.html
> +        긴 시간동안 함께해야 하는데 잘 지냈으면 좋겠습니다.
greate

2021-07-21 23:24 UTC, kimdaehee90 commented on self-introduction.html
> +자기소개서
ok

2021-07-21 23:24 UTC, kimdaehee90 commented on self-introduction.html
> +        긴 시간동안 함께해야 하는데 잘 지냈으면 좋겠습니다.
thanks

2021-07-22 01:53 UTC, burnyst approved these changes
great!

2021-07-22 01:55 UTC, merged